# Generated by Django 5.1.1 on 2025-02-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagevisit",
            name="cookies_accepted",
            field=models.BooleanField(default=False),
        ),
    ]
